.circleci/config.yaml
.gitignore
scripts/helm-releases.sh

create releases and update index.yaml
makes github pages helm repo

publish helm charts

---

charts/lotus-fullnode/Chart.yaml
charts/lotus-fullnode/templates/deployment-secrets.yaml

jobs are immutable and will cause an error on upgrade if any template variables change.
for example updating the docker image will cause this error

don't template jobs if they exist

---

charts/visor/Chart.yaml
charts/visor/templates/service-metrics.yaml
charts/visor/templates/service-monitor.yaml

visor is using defualt prom scrape endpoint so change it

use correct metrics scrape endpoint

---

charts/lotus-fullnode/Chart.yaml
charts/lotus-fullnode/templates/statefulset-daemon.yaml

this allows cloning volumes from other pvcs in the same namespace.
very useful for cloning lotus repos from synced noes

pvc datasource can now be configured

---

charts/lotus-fullnode/Chart.yaml
charts/lotus-fullnode/templates/service-load-balancer.yaml
charts/lotus-fullnode/values.yaml

a TCP load balancer for lotus libp2p

load balancer service for libp2p

---

charts/visor/Chart.yaml
charts/visor/templates/deployment.yaml
charts/visor/values.yaml

* specify a secret name containing JWT token
* fix bug in database configuration

make visor configurable to use any lotus-fullnode or db

---

charts/lotus-fullnode/Chart.yaml
charts/lotus-fullnode/templates/statefulset-daemon.yaml
charts/lotus-fullnode/values.yaml

lotus-fullnode: allow custom configs

---

charts/lotus-stats/.helmignore
charts/lotus-stats/Chart.yaml
charts/lotus-stats/README.md
charts/lotus-stats/templates/_helpers.tpl
charts/lotus-stats/templates/deployment.yaml
charts/lotus-stats/values.yaml

This is a basic lotus stats chart that provides the data ingestion service, it depends on https://github.com/filecoin-project/lotus/pull/4718

Add lotus-stats chart

---

charts/lotus-stats/Chart.yaml
charts/lotus-stats/templates/deployment.yaml

Per the values file, this should be `influxDatabase`.

lotus-stats: update influx database to correct value

---

charts/volume-snapshotter/.helmignore
charts/volume-snapshotter/Chart.yaml
charts/volume-snapshotter/README.md
charts/volume-snapshotter/templates/_helpers.tpl
charts/volume-snapshotter/templates/cronjob.yaml
charts/volume-snapshotter/values.yaml

The volume snapshotter chart provides a cronjob to rotate through volumesnapshots of pvc resources.

add volume-snapshotter chart

---

charts/sentinel-tick/Chart.yaml
charts/sentinel-tick/templates/deployment.yaml
charts/sentinel-tick/templates/service-metrics.yaml
charts/sentinel-tick/templates/service-monitor.yaml
charts/sentinel-tick/values.yaml

Copied from `visor`, tested in staging.

sentinel-tick: add prometheus support

---

charts/lotus-fullnode/Chart.yaml
charts/lotus-fullnode/templates/statefulset-daemon.yaml
charts/lotus-fullnode/values.yaml

allows attaching arbitrary volumes and volume mounts to the the lotus daemon.
provides commented out example in values.yaml

add a values stanza for additional volumes

---

charts/visor/Chart.yaml
charts/visor/templates/deployment.yaml
charts/visor/values.yaml

This is to support the changes made in https://github.com/filecoin-project/sentinel-visor/pull/464 which are expected to land in visor v0.6.0

feat: support revised visor flags as part of lily changes

---

charts/dealbot/Chart.yaml
charts/dealbot/templates/deployment.yaml
charts/dealbot/templates/service.yaml

* Add a different listening port
* Needs ingress values updated to allow access to this port (can be mounted at the `/graphql` path)
* Should not be behind basic auth

add graphql port to dealbot

---

charts/dealbot/Chart.yaml
charts/dealbot/templates/service.yaml
charts/dealbot/values.yaml

implements https://github.com/filecoin-project/lotus-infra/issues/328

external dns for graphql port

---

charts/sentinel-locations/.helmignore
charts/sentinel-locations/Chart.yaml
charts/sentinel-locations/templates/_helpers.tpl
charts/sentinel-locations/templates/deployment.yaml
charts/sentinel-locations/values.yaml

This adds a cronjob helm chart for sentinel-locations: https://github.com/filecoin-project/sentinel-locations.

sentinel-locations cron job

---

charts/lotus-mpool-stats/Chart.yaml
charts/lotus-mpool-stats/README.md
charts/lotus-mpool-stats/templates/_helpers.tpl
charts/lotus-mpool-stats/templates/deployment.yaml
charts/lotus-mpool-stats/templates/service-monitor.yaml
charts/lotus-mpool-stats/values.yaml

Cribbed generously from https://github.com/filecoin-project/helm-charts/tree/master/charts/lotus-stats 😅

feat: Add chart for lotus-mpool-stats

---

charts/dealbot/Chart.yaml
charts/dealbot/templates/deployment.yaml

should always be set kubernetes so no templating is required

sets DEALBOT_DAEMON_DRIVER to kubernetes

---

charts/dealbot/Chart.yaml
charts/dealbot/templates/deployment.yaml
charts/dealbot/values.yaml

Need to deploy this once https://github.com/filecoin-project/dealbot/pull/240 is merged

include kubeconfig

---

charts/dealbot/Chart.yaml
charts/dealbot/templates/deployment.yaml

indentation issue still wasn't fixed
this fixes it and is confirmed by a test deploy

fix indentation issue AGAIN

---

charts/lotus-bundle/Chart.yaml
charts/lotus-bundle/templates/statefulset.yaml
charts/lotus-bundle/values.yaml

Mount the existing lotus path into the filebeat sidecar so it can be included in filebeat configs.
https://github.com/filecoin-project/dealbot/issues/297

mount the lotus-path in filebeat

---

charts/lotus-bundle/Chart.yaml
charts/lotus-bundle/templates/statefulset.yaml
charts/lotus-bundle/values.yaml

make lotus imagePullPolicy configurable, and by default Always pull.

by default imagePullPolicy Always

---

charts/lotus-mpool-stats/Chart.yaml
charts/lotus-mpool-stats/templates/_helpers.tpl
charts/lotus-mpool-stats/templates/deployment.yaml
charts/lotus-mpool-stats/values.yaml

Also, bump to latest app version.

lotus-mpool-stats chart support configurable labels

---

charts/lotus-bundle/Chart.yaml
charts/lotus-bundle/templates/configmaps.yaml
charts/lotus-bundle/templates/statefulset.yaml
charts/lotus-bundle/values.yaml

Add an initContainers section.

enable initContainers

---

charts/filsnap/.helmignore
charts/filsnap/Chart.yaml
charts/filsnap/templates/NOTES.txt
charts/filsnap/templates/_helpers.tpl
charts/filsnap/templates/nodelocker/deployment.yaml
charts/filsnap/templates/nodelocker/service.yaml
charts/filsnap/templates/nodelocker/serviceaccount.yaml
charts/filsnap/templates/snapshots/configmap.yaml
charts/filsnap/templates/snapshots/cronjob.yaml
charts/filsnap/templates/snapshots/secret.yaml
charts/filsnap/values.yaml

This chart is for https://github.com/travisperson/filsnap
The chart will release a v1.0.0 when after filsnap is moved to the filecoin-project (https://github.com/travisperson/filsnap/issues/1) and releases a v1.0.0 itself.

initial filsnap chart with nodelocker deployment

---

charts/lily/templates/configmap-daemonconfig.yaml
charts/lily/values.yaml

- required by: https://github.com/filecoin-project/lily/pull/929
- closes https://github.com/filecoin-project/helm-charts/issues/148

feat: add config values for queue

---

charts/filsnap/Chart.yaml
charts/filsnap/templates/_helpers.tpl
charts/filsnap/templates/nodelocker/deployment.yaml
charts/filsnap/templates/nodelocker/service.yaml
charts/filsnap/templates/nodelocker/serviceaccount.yaml
charts/filsnap/templates/snapshots/configmap.yaml
charts/filsnap/templates/snapshots/cronjob.yaml
charts/filsnap/templates/snapshots/secret.yaml
charts/filsnap/values.yaml

filsnap has moved and been renamed from travisperson/filsnap to filecoin-project/filecoin-chain-archiver

filecoin-chain-archiver: rename from filsnap

---

charts/filecoin-chain-archiver/templates/snapshots/cronjob.yaml
charts/filecoin-chain-archiver/values.yaml

https://github.com/filecoin-project/helm-charts/issues/150

filecoin-chain-archiver: add activeDeadlineSeconds

---

charts/lily/templates/common/_app_template.tpl

Noticed that the Endpoints were not being correctly set and found that labels were not correct. While there, I noticed the args were very wrong. Both are now fixed.

fix(lily): Labels and args not properly set on lily nodes

---

charts/lily/templates/NOTES.txt
charts/lily/templates/common/_app_template.tpl
charts/lily/templates/common/_helpers.tpl
charts/lily/values.yaml

This includes a new option which disables bootstrapping. Also found a few more whitespace bugs with labels/args. #thxyaml

feat(lily): option to disable network sync

---

charts/lily/Chart.yaml
charts/lily/templates/common/_helpers.tpl

Release v0.1.4
- [fix(lily): Remove command args from tipset-worker job start script](https://github.com/filecoin-project/helm-charts/commit/cfdc4f05e6fc60bb1391eb6e5a5156be4be3cd81)

chore: Release Lily v0.1.4

---

charts/lily/templates/common/_app_template.tpl

closes https://github.com/filecoin-project/sentinel-infra/issues/289

feat(lily): Include startup checks for redis and postgres servers

---

charts/lily/templates/common/_app_template.tpl
charts/lily/templates/common/_helpers.tpl
charts/lily/values.yaml

feat(lily): Support lily log set-level-regex in chart

---

charts/lotus-bundle/Chart.yaml
charts/lotus-bundle/templates/ingress.yaml
charts/lotus-bundle/values.yaml
charts/lotus-fullnode/values.yaml

support multiple ingresses for bundled applications.
Just like the services list, provide a list of ingresses.

multiple ingresses

---

charts/lotus-bundle/Chart.yaml
charts/lotus-bundle/templates/statefulset.yaml

- ingress annotations
- use new snapshot source

support ingress annotations

---

charts/lotus-fullnode/Chart.yaml

no change here.
I changed CircleCI configuration, and I want to make sure the chart release workflow is working.

increase fullnode chart version

---

charts/lotus-bundle/Chart.yaml
charts/lotus-bundle/templates/service-monitor.yaml
charts/lotus-bundle/templates/statefulset.yaml

* add another service monitor
* map api port in lotus container

enable prometheus metrics for lotus

---

charts/lotus-bundle/Chart.yaml
charts/lotus-bundle/templates/service-monitor.yaml

error in yaml caused a rendering error.
this fixes it

remove duplcate key
