.circleci/config.yml, .cr-index/index.yaml, scripts/helm-releases.sh, scripts/lint.sh
* rename circle config yaml extension
* alter script to be resilient to cr errors, such as when a release
already exists. also need to persist a valid index.yaml for cr index
command. unsure why it seems to fetch the index.yaml from the github
pages branch. need to keep an eye on future behaviour as we release new
versions of charts
=> bug fixes to ci publishing

charts/lotus-fullnode/Chart.yaml, charts/lotus-fullnode/templates/statefulset-daemon.yaml, charts/lotus-fullnode/values.yaml
This will allow for custom arguments to be passed to the lotus daemon. At the moment this will generally be `--profile=bootstrap`.
=> lotus-fullnode: add support for specifying lotus daemon arguments

charts/lotus-fullnode/Chart.yaml, charts/lotus-fullnode/templates/statefulset-daemon.yaml, charts/lotus-fullnode/values.yaml
Pretty basic, I only added to this to the daemon as I don't see much of a reason to support it else where at the moment.
=> lotus-fullnode: add support for specifying env vars to the lotus daemon

charts/lotus-fullnode/Chart.yaml, charts/lotus-fullnode/templates/service-daemon.yaml, charts/lotus-fullnode/templates/statefulset-daemon.yaml, charts/lotus-fullnode/values.yaml
I'm still not sure of the proper pattern for labels, but this is at least a start to support adding custom labels to the daemon pod and service in front of it.
=> lotus-fullnode: add support for additional labels

charts/lotus-fullnode/Chart.yaml, charts/lotus-fullnode/templates/deployment-secrets.yaml
This works, you'll have to ask the helm community why.
=> lotus-fullnode: do not create job if secrets already exists

charts/lotus-chain-export/Chart.yaml, charts/lotus-chain-export/templates/cronjob.yaml
Only run chain exporting on cluster ip services.
=> lotus-chain-export: only export from ClusterIP

charts/lotus-consensus-check/Chart.yaml, charts/lotus-consensus-check/templates/cronjob.yaml
When running a LoadBalancer service inside of a namespace we see multiaddr construction for the consensus checker chart constructed like:
```
/ip4/172.20.65.184/tcp/1234/http
/ip4/172.20.195.235/tcp//http
/ip4/172.20.56.234/tcp/1234/http
/ip4/172.20.7.36/tcp//http
```
This is because the resource labels are exactly the same and we can't different between them. This introduces further filtering on the returned services to only construct multi addrs for services of type `ClusterIP`.
=> lotus-consensus-check: only select ClusterIP services

charts/visor/Chart.yaml, charts/visor/templates/deployment.yaml
For context https://github.com/filecoin-project/sentinel-visor/pull/116 is setting defaults to off for all types of task
=> feat(visor): don't rely on visor default values for head and history indexing

charts/lotus-fullnode/Chart.yaml, charts/lotus-fullnode/templates/statefulset-daemon.yaml, charts/lotus-fullnode/values.yaml
Parameters were not on a volume which resulted in them being downloaded on every pod restart.
=> Add parameter volume to lotus-fullnode chart

charts/lotus-fullnode/Chart.yaml, charts/lotus-fullnode/README.md, charts/lotus-fullnode/templates/NOTES.txt, charts/lotus-fullnode/templates/statefulset-daemon.yaml, charts/lotus-fullnode/values.yaml, charts/lotus-secrets-creator/.helmignore, charts/lotus-secrets-creator/Chart.yaml, charts/lotus-secrets-creator/README.md, charts/lotus-secrets-creator/templates/NOTES.txt, charts/lotus-secrets-creator/templates/_helpers.tpl, charts/lotus-secrets-creator/templates/deployment-secrets.yaml, charts/lotus-secrets-creator/values.yaml
This removes the default secret generation out of the lotus-fullnode chart. By default now, temporary secrets will be created, and it's on the user to create more permanent secrets for libp2p identities and jwt tokens.
=> Move secret generation out of lotus-fullnode chart

charts/visor/Chart.yaml, charts/visor/templates/deployment.yaml, charts/visor/values.yaml
This PR does a few things on the Visor chart:
- removes `run` options in favor of `walk` and `watch` options
- moves non-sensitive options to be args instead of envs to ensure runtime failure on unexpected inputs (instead of silently failing when the env interface changes)
- adds namespace checks on nested values
- adds validations on required or mutually exclusive inputs
- add some organization and comments
=> feat(visor): Update chart for visor@v0.4

charts/visor/Chart.yaml, charts/visor/README.md
In hindsight, given the drastic change in the chart API in https://github.com/filecoin-project/helm-charts/pull/45, it's probably best for us to bump the major version and not just the revision. This does that.
=> chore(visor): Bump visor chart major version

charts/lotus-fullnode/Chart.yaml, charts/lotus-fullnode/README.md, charts/lotus-fullnode/templates/NOTES.txt, charts/lotus-fullnode/templates/statefulset-daemon.yaml, charts/lotus-fullnode/values.yaml
This changes the way wallets are imported. Instead of having to list out the keys and file paths, instead the user just needs to provide a secret name. The value of each entry should be the base64 encoding of the keyinfo provided by wallets created with lotus-shed or from lotus wallet exports. 
Also adds a way to download a genesis.car file from a url. For example, setting `genesis.configMapName=localnet-genesis`, with the following configmap will download the genesis at the url, and place it under `/genesis/genesis.car`
```
apiVersion: v1
kind: ConfigMap
metadata:
name: localnet-genesis
data:
genesis: http://something.default.svc.cluster.local/genesis.car
```
=> Change the way wallet are imported

charts/lotus-fullnode/templates/statefulset-daemon.yaml, charts/lotus-fullnode/values.yaml
Adds the ability to run a disputer along side a fullnode.
=> Add disputer to lotus fullnode

charts/lotus-fullnode/Chart.yaml, charts/lotus-fullnode/templates/statefulset-daemon.yaml, charts/lotus-fullnode/values.yaml
This adds a feature to allow for enabling an easy datastore reset. When a `.reset` file is present in the datastore directory, the entire datastore will be removed as the first init container. This coupled with the snapshot import feature allows for easy resetting of a datastore and import of a snapshot.
Also, when a snapshot import is performed, a `.imported` file will be created in the datastore. This will stop further imports from taking place.
With `.reset` deleteing all files in the datastore directory, this will ensure that on every reset, an import is also performed.
=> Allow for easy reset of lotus datastore and manage importing

charts/visor/Chart.yaml, charts/visor/templates/deployment.yaml, charts/visor/values.yaml
Some improvements to the `visor` chart:
- Expose `GOLOG_LOG_FMT` as config key `logFormat`
- Remove DB init as we are handling it manually for now
- Value for config key `pgDatabase` now defaults to Secret key `database`
- Fix captialization for consistency
=> feat(visor): Expose visor log format config; remove DB init container; chores

charts/visor/Chart.yaml, charts/visor/templates/deployment.yaml, charts/visor/values.yaml
Use "recreate" deployment strategy to ensure that visor instances do not co-exist during an update. Necessary for analysis environments where multiple instances would duplicate data.
This PR is primarily for discussion around the change (if needed) with follow-on PRs which apply this chart to our staging/production deployments.
=> feat(visor): Use recreate strategy on visor chart

charts/lotus-fullnode/templates/statefulset-daemon.yaml, charts/lotus-fullnode/values.yaml
This PR adds a new snapshot import method is particularly for non-archive nodes.
This init container is intended to look and behave like the `chain-import` container already in use. Both containers use a the same `_imported` file to gate whether an import has already taken place, but the parameters required to configure the container are different. Whereas `chain-import` needs several pieces of information to get the snapshot volume, `trusted-chain-import` needs only a url.
The node is able to download the snapshot and get fully caught up in about half an hour using the "lightweight" snapshot. This initialization is suitable for applications that would require a lotus node, but don't require the additional volumes and processes required to manage an archive node.
=> importTrustedSnapshot

charts/lotus-gateway/Chart.yaml, charts/lotus-gateway/templates/deployment-gateway.yaml, charts/lotus-gateway/templates/service-gateway.yaml, charts/lotus-gateway/values.yaml
This adds a load balancer service as well as adding a `gatewayEnvs` value for setting additional environment variables such as golog formatting for json logs.
=> Add options to run load balancer service instead of ingress

charts/lotus-fullnode/templates/statefulset-daemon.yaml
This was a for which the script would fail right at the end, causing the
_imported file to never be created
=> fix import bug

charts/lotus-fullnode/templates/statefulset-daemon.yaml, charts/lotus-fullnode/values.yaml
By moving wallet management from init to runtime container, we can manage live wallets. This will be useful for applications that want a lotus node to send messages through and periodically rotate the wallet being used.
Something that might be worth considering is that I have marked the keystore volume read-write where it had previously been read-only.
If we want to keep the keystore RO for security reasons on nodes that don't need rotating keys, we could alternatively have wallet management as an init container OR runtime container and have the feature selectable by the values.yaml.
=> wallet updater

charts/lotus-bundle/Chart.yaml, charts/lotus-bundle/README.md, charts/lotus-bundle/templates/NOTES.txt, charts/lotus-bundle/templates/configmaps.yaml, charts/lotus-bundle/templates/deployment.yaml, charts/lotus-bundle/templates/filebeat-config.yaml, charts/lotus-bundle/templates/ingress.yaml, charts/lotus-bundle/templates/secrets.yaml, charts/lotus-bundle/templates/service-monitor.yaml, charts/lotus-bundle/templates/service.yaml, charts/lotus-bundle/templates/statefulset.yaml, charts/lotus-bundle/templates/wallets.yaml, charts/lotus-bundle/values.yaml
This is a helm chart to help you bundle your application with lotus along-side it.
Think of this as a decorator or a wrapper for lotus apps.
Key details:
* lotus can run stand-alone or lite mode
* Wallets are persisted to secrets, but they do not need to exist in advance
* Does not depend on any existing infra -- would work in other kubernetes clusters, etc outside of PL, etc.
* Applications that want to make deals have easy storage-volume to share the data.
* There is relatively little configuration options for lotus compared to the lotus-fullnode chart. Hopefully that makes this easier to use
In service of making things consumable outside of PL, This uses the docker image from https://github.com/filecoin-project/lotus/pull/6544 . Any change made there, could necessitate a change here. …
=> lotus bundle chart

charts/dealbot/Chart.yaml, charts/dealbot/templates/deployment.yaml, charts/dealbot/values.yaml
allows specifying a secret containing aws credentials necessary to deploy daemons on EKS
sets environment variables that can be used in kubeconfig
=> [DEALBOT] aws eks configuration in controller

charts/lotus-bundle/Chart.yaml, charts/lotus-bundle/templates/statefulset.yaml, charts/lotus-bundle/values.yaml
use emptyDir volumes by default so multiple containers can share storage
increase parameterization of application storage in values.yaml
now supports multiple volumes
=> make shared storage support ReadWriteMany

charts/lotus-bundle/Chart.yaml, charts/lotus-bundle/values.yaml
emptydir isn't big enough for our primary use of this chart.
this is a temporary fix and should be reverted back to emptydir as the generic chart default
=> use EFS for shared storage

charts/visor/Chart.yaml, charts/visor/templates/statefulset.yaml, charts/visor/values.yaml
Additional environment variables can be provided to the daemon by setting the `.daemon.env` value to an array of key-value pairs.
eg:
```
daemon:
env:
- name: NAME
value: value
```
=> add env value to daemon

charts/lily/Chart.yaml, charts/lily/templates/statefulset.yaml, charts/lily/values.yaml
This PR includes fixes for:
- Moving the jaeger tracing envvars for lily chart to the daemon container
- Make default image tag use chart appVersion
- Set default image tag in values to be empty
- Bump chart version (v0.0.3)
=> Fix tracing envvars; image tag defaults

charts/lily/Chart.yaml, charts/lily/templates/_helpers.tpl, charts/lily/templates/configmap-checkjob.yaml, charts/lily/templates/statefulset.yaml, charts/lily/values.yaml
Contains:
- Default tag is now `latest`
- Deployed `app.kubernetes.io/version` now uses the actually deployed value or defaults to chart version if missing
- Removed `awk` from processing job state in `waitjob.sh` ([comment](https://github.com/filecoin-project/lily/pull/731/files#r727572927))
- Include `waitjob.sh` in all lily containers
=> Update lily chart to v0.0.5

charts/lily/Chart.yaml, charts/lily/templates/_helpers.tpl, charts/lily/templates/configmap-waitjob.yaml, charts/lily/templates/cronjob-gapfill.yaml, charts/lily/templates/service-daemon-api.yaml
Fixes:
- And fix mismatched daemon api service endpoint
- Remove set -e as it was causing exits to fail in non-obvious ways,
plus we're already checking each exit code manually
- Interface for lily gap find/fill has changed and now the return stdout
is JSON. So we need to extract the ID w jq instead.
- Noticed it's possible for waitjob.sh to loop indefinately so I
added some precautions (change check to inspect for a true success case
instead of a true failure case (which includes other error cases
accidentally))
=> fix(lily): Repair gapfill cronjobs

charts/dealbot/Chart.yaml, charts/dealbot/templates/deployment.yaml, charts/dealbot/templates/service.yaml, charts/dealbot/values.yaml
Define a dedicated load balancer service for dealbot controller libp2p
host and configure a default listen multiaddr for the deployment object.
Bump the version of chart prior to release.
Relates to:
- https://github.com/filecoin-project/dealbot/issues/342
=> Define dealbot controller libp2p service

charts/dealbot/Chart.yaml, charts/dealbot/templates/service.yaml
Fix the incorrect placement of `annotation` key in dealbot services and
fix the indentation, which results in invalid yaml when more than one
annotation is specified.
=> Fix incorrect key placement and indentation in dealbot chart

charts/lily/Chart.yaml, charts/lily/templates/NOTES.txt, charts/lily/templates/_helpers.tpl, charts/lily/templates/statefulset.yaml, charts/lily/values.yaml
In this update:
- updated lily jaeger tracing parameter names
- deprecating `host` and `port`
- adding `providerUrl`
- chart uses `host` and `port` in new providerUrl param as `http://{host}:{port}/api/tracing`
- Added tracing params to NOTES.txt
- Reorganized snapshot import logic (all in one init container)
- Bump default app version to v0.8.6
- Bump chart version to v0.0.7
=> feat(lily): Meet lily v0.8.6 interface

charts/lily/templates/statefulset.yaml
Lily's jobs wait for chain sync before beginning immediately, however,
the datastore is still optimizing and executing jobs while the datastore
is thrashing the disk causes all jobs to perform poorly. This wait
allows the node to settle before becoming "ready" and running jobs.
=> feat(lily): Delay lily job startup

charts/lotus-bundle/Chart.yaml, charts/lotus-bundle/templates/statefulset.yaml, charts/lotus-bundle/values.yaml
This bundle is used by storetheindex. Template the ability to specify
readiness probe for the application container, needed by storetheindex.
This change is backward compatible.
It seems `container.application.resources` value exists but not templated. This PR also fixes that in the interest of faster turnaround.
=> Template the ability to specify readiness probe in lotus bundle

charts/lily/Chart.yaml, charts/lily/templates/common/_app_template.tpl, charts/lily/templates/common/_helpers.tpl, charts/lily/templates/daemon/metrics-service-monitor.yaml, charts/lily/templates/daemon/metrics-service.yaml, charts/lily/templates/notifier/metrics-service-monitor.yaml, charts/lily/templates/notifier/metrics-service.yaml, charts/lily/templates/worker/metrics-service-monitor.yaml, charts/lily/templates/worker/metrics-service.yaml, charts/lily/values.yaml
The following features were added:
- notifier instance has storage config included
- conditionally execute jobs based on the instance and job type combination
- For: only notifiers and standalone daemons should run the survey since it's never a queued job...
- create `init-sync` init step to break out the network sync behavior
- adjust conditional sync behavior
- more non-functional changes (whitespace adjustments, resource names, etc)
=> fix(lily): Notifier config includes storage settings

charts/lily/Chart.yaml
Here is an overview of improvements included on this release:
- feat: add static `ServiceMonitor`s for metrics scraping
- feat: separate sync behavior into `init-sync` from `init-datastore`
- fix: conditionally run jobs based on job/instance-type combination
- fix: explicitly set all REDIS env vars
- fix: instance-specific labels
- chore: adjust "sync wait" behavior on startup
- chore: lots of resource renaming, behavior reorg, whitespace, comment, echo improvements
- chore: reorganize debug values.yaml organization
=> chore(lily): Bump version to v0.1.3

charts/lily/templates/common/_app_template.tpl
This fixes some syntax bugs in Lily's `init-sync` script from the prior release.
=> fix(lily): Adjust init-sync script; Add termination grace period

charts/lotus-fullnode/Chart.yaml, charts/lotus-fullnode/values.yaml
Updating the default url for the Snapshot to the new URL of `https://snapshots.mainnet.filops.net/minimal/latest`. This is going to be used as the new default url to download the snapshots. 
Bumped the Chart Version number from `version: 0.3.4` to `version: 0.3.5`
=> Update the default URL for Full-Node Chart to the new Snapshot URL

charts/lotus-grafana/Chart.yaml, charts/lotus-grafana/README.md, charts/lotus-grafana/requirements.lock, charts/lotus-grafana/requirements.yaml, charts/lotus-grafana/templates/nginx-config-sidecar.yaml, charts/lotus-grafana/values.yaml
This primarily just updates the grafana chart version, but doing so adds some new features and a README has been added to give a quick run down of how to use them. This turns the grafana dashboard into a stateless application loading the datasources and dashboards on each startup. This is to try and make the dashboard easier to use in GitOps.
There is probably some more work that can be done to this chart to make things a little easier further.
For example the datasources and dashboards can be loaded via configmap completely as opposed to be defined in the values file (the config for each), and loaded through the various sides cars. Also I think we might be able to remove the nginx from the side car completely and run nginx alongside grafana in a separate pod. Right now you must know how …
=> chore: update grafana chart version

charts/lotus-bundle/Chart.yaml, charts/lotus-bundle/templates/ingress.yaml
ingress annotations are important to allow us to specify configuration to the ingress controller, e.g. to add HTTP headers.
=> ingress annotations

charts/filecoin-chain-archiver/Chart.yaml, charts/filecoin-chain-archiver/templates/reset-cronjob.yaml
the old name convention only left 6 characters for the lotus pod name after the prefix, causing failuresin deployments. inverse truncation ensures a unique name, preserving pod name indices
=> enforce char limit with inverse truncation

charts/lotus-fullnode/Chart.yaml, charts/lotus-fullnode/templates/statefulset-daemon.yaml
move erroneously places fields from inside the .spec.template.spec.containers array to where they belong: spec.template.spec
e.g. spec.template.spec.containers[?].nodeSelector -> spec.template.spec.nodeSelector
=> Fix syntax error in lotus-fullnode sts 0.4.1

charts/filecoin-chain-archiver/Chart.yaml, charts/filecoin-chain-archiver/templates/_helpers.tpl, charts/filecoin-chain-archiver/templates/reset-cronjob.yaml, charts/filecoin-chain-archiver/values.yaml
use a template function and include to truncate datastore reset names. ensure the serviceaccount related name references match.
=> template function for truncated name used by reset cronjobs

charts/lotus-bundle/CHANGELOG.md, charts/lotus-bundle/Chart.yaml, charts/lotus-bundle/templates/statefulset.yaml
the date_initialized file would be created and block future imports, even if the snapshot import fails.
* configure bash properly, so there's better logging and scripts exit on failures
* create data_initialized in the datastore directory, and remove the redundant step of having to delete it during the reset-datastore initContainer
=> fix flakey snapshot import behavior

charts/lotus-bundle/Chart.yaml, charts/lotus-bundle/templates/service-monitor.yaml
the lotus node should ideally be local to the pod only.
adding a service only for prometheus scraping seems like the wrong choice, so let's try a PodMonitor instead
=> use a pod monitor instead of a service monitor

charts/lotus-bundle/Chart.yaml, charts/lotus-bundle/templates/service-monitor.yaml
should be 'podMetricsEndpoints' instead of
=> pod monitor uses different endpoint name

charts/lotus-bundle/Chart.yaml, charts/lotus-bundle/templates/_helpers.tpl, charts/lotus-bundle/templates/statefulset.yaml, charts/lotus-bundle/values.yaml
Add a function to allow us to inject environment variables more "naturally" into container specs.
Example use
(adapted from
https://github.com/k8s-at-home/library-charts/blob/ 1b8b81ceb368e378c01aaf826142cfd948a93042/charts/stable/common/ templates/lib/controller/_env_vars.tpl)
=> Add lotus-bundle.env_vars helper function

charts/filecoin-chain-archiver/Chart.yaml, charts/filecoin-chain-archiver/templates/reset-cronjob.yaml, charts/filecoin-chain-archiver/templates/snapshots/cronjob.yaml, charts/lotus-chain-export/Chart.yaml, charts/lotus-chain-export/templates/cronjob.yaml, charts/lotus-consensus-check/Chart.yaml, charts/lotus-consensus-check/templates/cronjob.yaml, charts/nebula-crawler/Chart.yaml, charts/nebula-crawler/templates/cron.yaml, charts/sentinel-locations/Chart.yaml, charts/sentinel-locations/templates/deployment.yaml, charts/volume-snapshotter/Chart.yaml, charts/volume-snapshotter/templates/cronjob.yaml
- update CronJob api version to `batch/v1`. `batch/v1beta1` is deprecated since Kubernetes v1.21 and unavailable in v1.25.
- add labels jobTemplate. This will allow kube-state-metrics for CronJob & Job to be joined and detect failed cron job runs.
=> chore: update CronJob api version to batch/v1 and add labels jobTemplate

charts/lotus-bundle/CHANGELOG.md, charts/lotus-bundle/Chart.yaml, charts/lotus-bundle/templates/_helpers.tpl, charts/lotus-bundle/templates/configmaps.yaml, charts/lotus-bundle/templates/statefulset.yaml, charts/lotus-bundle/values.yaml
- This shouldn't be necessary since Lotus should respect envvar
configurations but lotus 1.23.3 introduces a validation bug
preventing Lotus running if there's no uncommented
`EnableSplitstore` field in the config file
- Add exemplary config derived from chain.love
https://github.com/filecoin-project/lotus/issues/11198
=> Support injecting a lotus config file via values

charts/lotus-bundle/CHANGELOG.md, charts/lotus-bundle/Chart.yaml, charts/lotus-bundle/values.yaml
- Don't enable FEVM by default
- Fix erroneous configmap name override in default values
- Remove chain.love defaults until there's a plan for managing this
chart going forward #225
=> Fix erroneous changes in lotus-bundle 0.1.4

charts/lotus-bundle/CHANGELOG.md, charts/lotus-bundle/Chart.yaml, charts/lotus-bundle/templates/statefulset.yaml, charts/lotus-bundle/values.yaml
- Allow user to pass USE_ARIA2C="true" to make the snapshot downloader use
aria2c, speediing up the download significantly. Note this will cause a
container runtime installation of aria2c before snapshot download. This
is less than ideal, but the snapshot downloader would require a lotus-based
image including aria2c which is nontrivial to produce.
=> lotus-bundle: Add arai2c support
